// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmhwfdupsyobqoacjdbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttaHdmZHVwc3lvYnFvYWNqZGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzM1OTIsImV4cCI6MjA2NjQ0OTU5Mn0._GQZOcEypM3OxvfHa4uPm-bCjcNn3i8bsRTuAN8pN84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);