// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prbeszbotzzyhglezdbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByYmVzemJvdHp6eWhnbGV6ZGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODMxNjgsImV4cCI6MjA2NTg1OTE2OH0.iEdo8sELyjC4qlbWD5YvAzA9Z0Q5L3g7Nz7Ge0VHlCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);